apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sample-app2
  namespace: sample-app
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sample-app
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: sample-app-helm-chart
        namespace: flux-system
  values: {} 